# Generated by Django 4.2.4 on 2023-10-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
